language: go
go: 1.3

# let us have pretty experimental Docker-based Travis workers
sudo: false

env:
    - TRAVIS_GLOBAL_WTF=1
    - _GOOS=linux _GOARCH=amd64
    - _GOOS=linux _GOARCH=386 # CGO_ENABLED=1 # TODO add this once Travis can handle it (ie, has the headers and stuff we need - see https://travis-ci.org/tianon/libcontainer/jobs/30126518#L167 "pkg/runtime/cgo/cgo.go:26:46: fatal error: sys/types.h: No such file or directory")
#    - _GOOS=linux _GOARCH=arm # see https://github.com/moovweb/gvm/issues/22

install:
    - mkdir -pv "${GOPATH%%:*}/src/github.com/docker" && [ -d "${GOPATH%%:*}/src/github.com/docker/libcontainer" ] || ln -sv "$(readlink -f .)" "${GOPATH%%:*}/src/github.com/docker/libcontainer"
    - if [ -z "$TRAVIS_GLOBAL_WTF" ]; then
          gvm cross "$_GOOS" "$_GOARCH";
          export GOOS="$_GOOS" GOARCH="$_GOARCH";
      fi
    - if [ -z "$TRAVIS_GLOBAL_WTF" ]; then go env; fi
    - go get -d -v ./...
    - if [ "$TRAVIS_GLOBAL_WTF" ]; then
          export DOCKER_PATH="${GOPATH%%:*}/src/github.com/dotcloud/docker";
          mkdir -p "$DOCKER_PATH/hack/make";
          ( cd "$DOCKER_PATH/hack/make" && wget -c 'https://raw.githubusercontent.com/dotcloud/docker/master/hack/make/'{.validate,validate-dco,validate-gofmt} );
          sed -i 's!dotcloud/docker!docker/libcontainer!' "$DOCKER_PATH/hack/make/.validate";
      fi

script:
    - if [ "$TRAVIS_GLOBAL_WTF" ]; then bash "$DOCKER_PATH/hack/make/validate-dco"; fi
    - if [ "$TRAVIS_GLOBAL_WTF" ]; then bash "$DOCKER_PATH/hack/make/validate-gofmt"; fi
    - if [ -z "$TRAVIS_GLOBAL_WTF" ]; then go build -v ./...; fi
    - if [ -z "$TRAVIS_GLOBAL_WTF" ]; then go test -v ./...; fi
